name: Audio Processing Workflow

on:
  push:
    paths:
      - 'audio.wav'  # Trigger workflow when audio.wav is uploaded

jobs:
  process-audio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pydub deepgram-sdk google-generativeai

      - name: Run audio processing script
        run: python process_audio.py

      - name: Commit response
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add response.mp3
          git commit -m "Add response audio"
          git push
